
export const ROLES = [
  "web-designer",
  "ui-ux-designer",
  "graphic-designer",
  "wordpress-developer",
  "shopify-developer",
  "frontend-developer",
  "backend-developer",
  "mobile-app-developer",
  "seo-specialist",
  "content-writer",
  "copywriter",
  "video-editor",
  "social-media-manager",
  "virtual-assistant",
  "data-analyst",
  "product-designer",
  "branding-designer",
  "email-marketer",
  "qa-tester",
  "devops-engineer",
] as const;

export const ROLE_LABEL: Record<(typeof ROLES)[number], string> = {
  "web-designer": "Web Designer",
  "ui-ux-designer": "UI/UX Designer",
  "graphic-designer": "Graphic Designer",
  "wordpress-developer": "WordPress Developer",
  "shopify-developer": "Shopify Developer",
  "frontend-developer": "Front-End Developer",
  "backend-developer": "Back-End Developer",
  "mobile-app-developer": "Mobile App Developer",
  "seo-specialist": "SEO Specialist",
  "content-writer": "Content Writer",
  "copywriter": "Copywriter",
  "video-editor": "Video Editor",
  "social-media-manager": "Social Media Manager",
  "virtual-assistant": "Virtual Assistant",
  "data-analyst": "Data Analyst",
  "product-designer": "Product Designer",
  "branding-designer": "Branding Designer",
  "email-marketer": "Email Marketer",
  "qa-tester": "QA Tester",
  "devops-engineer": "DevOps Engineer",
};
